# Generated by Django 3.2.3 on 2021-07-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
