# Generated by Django 3.2.3 on 2021-07-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('reserve_datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('people_quantity', models.PositiveIntegerField(verbose_name='Количество людей')),
                ('phone_number', models.PositiveIntegerField(verbose_name='Номер телефона')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='user_reserve')),
            ],
        ),
    ]
