# Generated by Django 3.2.3 on 2021-07-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии к заказу'),
        ),
    ]
