# Generated by Django 3.2.3 on 2021-07-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_history_of_order_reserve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History_of_order',
        ),
    ]
