# Generated by Django 3.2.3 on 2021-07-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_delete_history_of_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
