# Generated by Django 3.2.3 on 2021-07-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
